#!/usr/bin/env node
/**
 * build.mjs — assemble cf-site/dist from /home/claude/build.
 *
 * The Worker serves dist/ with html_handling:"auto-trailing-slash", so
 * /privacy is the canonical URL and /privacy.html 307s to it. Every
 * in-page link is rewritten to the clean form here, in one place, so the
 * two copies of the site can never drift apart by hand again.
 */
import fs from "node:fs";
import path from "node:path";

// SRC is the repo root (pages with .html links, the GitHub Pages standby).
// DIST is what wrangler uploads. Override either with an env var.
// ── HOW THIS RUNS IN WORKERS BUILDS ────────────────────────────────────────
// Cloudflare builds this repo on every push to main. The dashboard's build
// command sets BOTH variables explicitly:
//
//   KNOX_SRC=. KNOX_DIST=cf/dist node cf/build.mjs
//   npx wrangler deploy --config cf/wrangler.jsonc
//
// Neither is optional. The defaults below are absolute paths from the machine
// this script was written on and exist nowhere else, so a build that forgets
// them reads from a directory that is not there. And the deploy MUST carry
// --config: wrangler.jsonc lives in cf/, not at the repo root, and its
// `main` and `assets.directory` resolve relative to itself — pointing wrangler
// anywhere else silently drops src/router.js, which is what serves all seven
// /thevault/<demo> mounts.
const SRC = process.env.KNOX_SRC || "/home/claude/build";
const DIST = process.env.KNOX_DIST || "/home/claude/cf-site/dist";

/** Pages copied with link rewriting. */
const PAGES = ["index.html", "privacy.html", "sms-terms.html", "thevault.html", "how.html", "getting-found.html", "404.html"];

/** Copied byte-for-byte. */
const VERBATIM = ["favicon.png", "knox-logo.png", "robots.txt", "sitemap.xml", "_headers"];

/** Asset trees copied wholesale. `thevaultfilms/` holds the Screening Room film pages
 *  (dist/thevaultfilms/*.html); the worker 301s the old /thevault/films URLs here.
 *
 *  The local-SEO directories below are generated by tools/build-local-pages.mjs and
 *  committed. They ship as TREES rather than PAGES for two reasons: the PAGES loop
 *  has no mkdirSync and would throw ENOENT on a nested path, and these pages already
 *  author clean URLs so they need no rewriting. The trade-off is that the
 *  "unrewritten links" guard below never sees them — that check is reimplemented as
 *  assertClean() inside the generator, and it must stay there.
 *
 *  NEVER name one of these after an existing page stem: a dist/<name>/ directory
 *  shadows <name>.html in the asset router (see the rmSync comment below). */
const TREES = ["assets", "thevaultfilms", "dupage-county", "glen-ellyn", "wheaton", "lombard"];

const CLEAN = [
  // Absolute self-references first: canonical, og:url, sitemap entries.
  [/https:\/\/getprojectknox\.com\/index\.html/g, "https://getprojectknox.com/"],
  [/https:\/\/getprojectknox\.com\/(privacy|sms-terms|thevault|how|getting-found)\.html/g, "https://getprojectknox.com/$1"],
  [/href="privacy\.html"/g, 'href="/privacy"'],
  [/href="\/privacy\.html"/g, 'href="/privacy"'],
  [/href="sms-terms\.html"/g, 'href="/sms-terms"'],
  [/href="\/sms-terms\.html"/g, 'href="/sms-terms"'],
  // Fragments matter: the homepage teaser chips deep-link to /thevault#chops.
  [/href="\/?thevault\.html(#[a-z-]*)?"/g, 'href="/thevault$1"'],
  [/href="\/?how\.html(#[a-z-]*)?"/g, 'href="/how$1"'],
  [/href="\/?getting-found\.html(#[a-z-]*)?"/g, 'href="/getting-found$1"'],
  // The home link carries fragments from other pages (index.html#contact → /#contact).
  [/href="index\.html(#[a-z-]*)?"/g, 'href="/$1"'],
];

function copyTree(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const e of fs.readdirSync(from, { withFileTypes: true })) {
    const a = path.join(from, e.name);
    const b = path.join(to, e.name);
    if (e.isDirectory()) copyTree(a, b);
    else fs.copyFileSync(a, b);
  }
}

// Start from nothing: a stale tree left in dist (like the old thevault/films
// pages after the Screening Room moved) would keep shipping forever — and a
// leftover thevault/ DIRECTORY shadows the thevault.html PAGE in the asset
// router. Clean, then build.
fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

for (const p of PAGES) {
  const src = path.join(SRC, p);
  if (!fs.existsSync(src)) {
    console.warn(`skip (missing): ${p}`);
    continue;
  }
  let html = fs.readFileSync(src, "utf8");
  for (const [re, to] of CLEAN) html = html.replace(re, to);

  // A stale .html link left anywhere is a 307 the visitor pays for.
  const leftover = html.match(/(href|content)="[^"]*(privacy|sms-terms|thevault|how|index|getting-found)\.html(#[a-z-]*)?"/g);
  if (leftover) throw new Error(`${p}: unrewritten links ${leftover.join(", ")}`);

  fs.writeFileSync(path.join(DIST, p), html);
  console.log(`page     ${p}  ${(Buffer.byteLength(html) / 1024).toFixed(1)} KB`);
}

for (const f of VERBATIM) {
  // _headers is Cloudflare-only config and lives in cf/ in the repo, but at
  // the source root in the working tree. Look in both, or a fresh clone
  // deploys without it and silently loses the immutable font caching.
  const src = [path.join(SRC, f), path.join(SRC, "cf", f)].find((p) => fs.existsSync(p));
  if (!src) {
    console.warn(`skip (missing): ${f}`);
    continue;
  }
  fs.copyFileSync(src, path.join(DIST, f));
  console.log(`verbatim ${f}`);
}

for (const t of TREES) {
  const src = path.join(SRC, t);
  if (!fs.existsSync(src)) continue;
  copyTree(src, path.join(DIST, t));
  console.log(`tree     ${t}/`);
}

console.log("dist ready");
